spring:

  application:
    name: WebApp

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/admindb
    username: postgres
    password: 2021

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: false